src/main/java/all/clear/controller/RequirementController.java
src/main/java/all/clear/controller/SubjectController.java
src/main/java/all/clear/controller/TimeTableController.java
src/main/java/all/clear/controller/UserController.java
src/main/java/all/clear/dto/responseDto/RequirementComponentResponseDto.java
src/main/java/all/clear/dto/responseDto/RequirementResponseDto.java
src/main/java/all/clear/global/exception/ErrorResponseDto.java
src/main/java/all/clear/global/exception/ExceptionAdvice.java
src/main/java/all/clear/global/exception/GlobalErrorCode.java
src/main/java/all/clear/global/exception/GlobalException.java
src/main/java/all/clear/global/exception/GlobalExceptionHandler.java
src/main/java/all/clear/global/exception/ResponseDto.java
src/main/java/all/clear/global/exception/SuccessCode.java
src/main/java/all/clear/global/response/ApiResponse.java
src/main/java/all/clear/repository/RequirementRepository.java
src/main/java/all/clear/service/RequirementService.java
src/test/java/all/clear/RequirementTest.java

- `RequirementResponseDto` 추가
- `RequirementComponentResponseDto` 추가
- `RequirementService`의 `getRequirement` method RequireResponseDto 반환하게 수정
- `RequirementResponseDto`에서 내부 List도 `RequirementComponentResponseDto`로 mapping
- 졸업요건 맨 윗 줄을 dto로 변환해 반환하는 테스트 코드 작성
- Exception 관련 파일 추가
- `ResponseDto` 추가
- ResponseDto 반환 함수 추가
- ApiResponse 함수 수정
- Controller annotation `RestController`으로 변경

[Add] 졸업요건 관련 DTO, ResponseDto 추가

---

src/main/java/all/clear/controller/GradeController.java
src/main/java/all/clear/controller/RequirementController.java
src/main/java/all/clear/crwal/CrawlMemberInfo.java
src/main/java/all/clear/crwal/ParsingRequirement.java
src/main/java/all/clear/dto/responseDto/grade/GradeResponseDto.java
src/main/java/all/clear/dto/responseDto/grade/SemesterGradeResponseDto.java
src/main/java/all/clear/dto/responseDto/grade/SemesterSubjectResponseDto.java
src/main/java/all/clear/dto/responseDto/requirement/RequirementComponentResponseDto.java
src/main/java/all/clear/dto/responseDto/requirement/RequirementResponseDto.java
src/main/java/all/clear/service/GradeService.java
src/main/java/all/clear/service/MemberService.java
src/main/java/all/clear/service/RequirementService.java
src/test/java/all/clear/CrawalTest.java
src/test/java/all/clear/RequirementTest.java

필드 정리
private Member member;
private Requirement requirement;
private Grade grade;
getter lombok 삭제하고 get 함수 추가
setter lombok삭제
접근지정자 설정
생성자에서 필드 초기화하도록 수정

[Chore] CralMemberInfo 코드 스타일 수정

---

.idea/encodings.xml
.idea/libraries/Gradle__org_springframework_boot_spring_boot_starter_security_3_1_3.xml
.idea/libraries/Gradle__org_springframework_security_spring_security_config_6_1_3.xml
.idea/libraries/Gradle__org_springframework_security_spring_security_core_6_1_3.xml
.idea/libraries/Gradle__org_springframework_security_spring_security_crypto_6_1_3.xml
.idea/libraries/Gradle__org_springframework_security_spring_security_web_6_1_3.xml
.idea/modules/all-clear.test.iml
.idea/modules/com.example.all-clear.main.iml
build.gradle
src/main/java/all/clear/controller/GradeController.java
src/main/java/all/clear/controller/MemberController.java
src/main/java/all/clear/controller/RequirementController.java
src/main/java/all/clear/crawl/CrawlMemberInfo.java
src/main/java/all/clear/crawl/ParsingRequirement.java
src/main/java/all/clear/domain/Member.java
src/main/java/all/clear/domain/UserDetailsImpl.java
src/main/java/all/clear/dto/requestDto/EmailIsValidRequestDto.java
src/main/java/all/clear/dto/requestDto/LoginRequestDto.java
src/main/java/all/clear/dto/requestDto/MemberSignupRequestDto.java
src/main/java/all/clear/dto/requestDto/UpdateRequestDto.java
src/main/java/all/clear/global/exception/GlobalErrorCode.java
src/main/java/all/clear/global/response/ApiResponse.java
src/main/java/all/clear/repository/MemberRepository.java
src/main/java/all/clear/service/MemberService.java
src/test/java/all/clear/CrawalTest.java
src/test/java/all/clear/RequirementTest.java

- Controller 완성
- Service 구현 중
- requestDto 수정 -> usaintId, usaintPassword 추가
- Controller 완성
- Service 완성 (토큰 관련 제외)
- UserDetails 추가
- security implement
- password Encoder 추가
- ApiMessage 인자 수정
- 회원가입 이메일 코드 발송하기
- 회원가입 이메일 코드 인증하기
- 회원가입 usaint 계정 확인하기 -> 성공 시 member 객체 set 
- 기타 추가 예외처리

[Feat] 회원가입, 로그인 기능 구현

---

src/main/java/all/clear/crawl/CrawlInfo.java
src/main/java/all/clear/crawl/CrawlMemberInfo.java
src/main/java/all/clear/crawl/CrawlTestInfo.java
src/test/java/all/clear/CrawalTest.java
src/test/java/all/clear/CrawlSpeedExceptionTest.java

1. 크롤링 시간 최적화
- CrawlMemberInfo에 있는 thread.sleep 코드 불필요한 부분 삭제 
2. 유세인트 업데이트 반영
- 학기별 성적 상세보기 변경 사항 반영해서 코드 수정 완료 
3. 크롤링 자체 테스트 코드 추가
-  CrawlInfo 클래스, CrawlSpeedExceptionTest 테스트코드 추가  <- 추후 유세인트 업데이트시 유지보수에 필요

크롤링 시간최적화, 유세인트 업데이트 반영, 크롤링 자체 테스트 코드 추가

---

.idea/misc.xml
src/main/java/allclear/crawl/CrawlMemberInfo.java
src/main/java/allclear/crawl/ParsingGrade.java
src/main/java/allclear/domain/grade/SemesterGrade.java

- 파싱 후 Grade 객체 반환 함수
- 테스트 코드 작성 테스트 필요
- 예외 전달 코드 작성
- 파싱 함수 테스트 코드
- 기타 예외 처리

[Feat] 성적 크롤링 데이터 파싱 함수 구현

---

src/main/java/allclear/crawl/CrawlMemberInfo.java
src/test/java/allclear/CrawalTest.java

- 학사 관리 버튼 클릭이 되지 않아 크롤링 진행 불가하던 에러 처리
- 크롤링 생성자 부분에서 파싱이 되지 않아 발생하는 에러 처리

[chore] : 크롤링 에러 처리

---

src/main/java/allclear/crawl/CrawlMemberInfo.java
src/main/java/allclear/crawl/ParsingGrade.java
src/main/java/allclear/crawl/ParsingRequirement.java
src/test/java/allclear/CrawalTest.java
src/test/java/allclear/ParsingTest.java

- List 값을 get()을 통해 가져올 때 NULL 값으로 인한 에러 처리
- 테스트 코드 작성
- Grade의 totalCredit 필드 타입 변경 필요
- 변경 후, 파싱 함수 일부 수정 필요

[Chore] Parsing 함수 에러 처리

---

src/main/java/allclear/crawl/CrawlMemberInfo.java
src/main/java/allclear/crawl/ParsingRequirement.java
src/test/java/allclear/crawl/ParsingTest.java

- 로그인 버튼 클릭 후 홈 버튼 클릭 처리 안될  경우 예외 처리
- 이수구분 추가

[Chore] 로그인 예외 처리

---

src/main/java/allclear/crawl/CrawlSubjectInfo.java
src/test/java/allclear/crawl/CrawlSubjectTest.java

- 학부 전공 과목 크롤링 임시 기능 추가
- 추후 학점, 시간 크롤링 기능 추가 및 교양 과목 등 크롤링 기능 추가

feat : CrawlSubjectInfo 과목 크롤링 기능 추가

---

src/main/java/allclear/crawl/CrawlSubjectInfo.java
src/test/java/allclear/crawl/CrawlSubjectTest.java

- 학부전공, 교양필수, 교양선택, 채플, 교직 크롤링 기능 구현
- 추후 크롤링 여부에 따라 함수 추가 필요
- 파싱 함수 구현 필요

[chore] : CrawlSubjectInfo 과목 크롤링 함수 추가

---

src/main/java/allclear/controller/AdminController.java
src/main/java/allclear/controller/SubjectController.java
src/main/java/allclear/dto/requestDto/subject/GetSubjectListRequestDto.java
src/main/java/allclear/repository/subject/SubjectRepository.java
src/main/java/allclear/repository/subject/SubjectSpecification.java
src/main/java/allclear/service/SubjectService.java

- Repository 구현
- Service 구현
- Controller 구현
- Service 구현
- Controller 구현
- /admin 으로 함

[Feat] Subject 기능 구현

---

src/main/java/allclear/domain/subject/Subject.java
src/main/java/allclear/domain/timetable/TimetableClassInfo.java
src/main/java/allclear/domain/timetable/TimetableSubject.java
src/main/java/allclear/dto/requestDto/timetable/AddCustomTimetableSubjectRequestDto.java
src/main/java/allclear/dto/requestDto/timetable/ClassInfoRequestDto.java
src/main/java/allclear/dto/requestDto/timetable/UpdateTimetableSubjectRequestDto.java
src/main/java/allclear/dto/responseDto/subject/ClassInfoResponseDto.java
src/main/java/allclear/dto/responseDto/timetable/TimetableSubjectResponseDto.java
src/main/java/allclear/service/TimetableService.java

TimetableSubject, Subject 각각 ClassInfo 구분

[Fix] Subject에서 ClassInfo 데이터베이스 반영 안됨 해결

---

src/main/java/allclear/domain/subject/ClassInfo.java
src/main/java/allclear/domain/timetable/TimetableSubject.java
src/main/java/allclear/service/TimetableService.java

[Fix] subject, timetableSubject id = null 수정

---

src/main/java/allclear/domain/grade/Grade.java
src/main/java/allclear/domain/grade/SemesterGrade.java
src/main/java/allclear/domain/grade/SemesterSubject.java
src/main/java/allclear/domain/member/Member.java
src/main/java/allclear/domain/requirement/Requirement.java
src/main/java/allclear/domain/requirement/RequirementComponent.java
src/main/java/allclear/domain/subject/ClassInfo.java
src/main/java/allclear/domain/timetable/Timetable.java
src/main/java/allclear/domain/timetable/TimetableClassInfo.java
src/main/java/allclear/domain/timetable/TimetableSubject.java

[Fix] 서버 오류 수정

---

src/main/java/allclear/crawl/CrawlMemberInfo.java
src/main/java/allclear/service/MemberService.java

- 유저 조회 예외 처리
- 유저 삭제 예외 처리
- 유저 업데이트 예외 처리
- 회원가입 실패 조건 변경 => 크롤링 실패 시 회원 가입 실패로 변경
- 파싱 함수의 인자가 null 인 경우 예외 처리

[Chore] : MemberService 예외 처리

---

src/main/java/allclear/domain/grade/Grade.java
src/main/java/allclear/domain/grade/SemesterGrade.java
src/main/java/allclear/domain/member/Member.java
src/main/java/allclear/domain/requirement/Requirement.java
src/main/java/allclear/repository/grade/GradeRepository.java
src/main/java/allclear/repository/requirement/RequirementRepository.java
src/main/java/allclear/service/MemberService.java

- grade 및 requirement 엔티티 DB에서 삭제 후 저장 기능으로 수정
- 고유키 중복 발생으로 인한 에러 처리

[Fix] 유저 업데이트 오류 수정 및 예외 처리 코드 수정

---

src/main/java/allclear/controller/SubjectController.java
src/main/java/allclear/crawl/CrawlMemberInfo.java
src/main/java/allclear/crawl/CrawlSubjectInfo.java
src/main/java/allclear/crawl/ParsingSubject.java
src/main/java/allclear/domain/subject/ClassInfo.java
src/main/java/allclear/global/exception/code/GlobalErrorCode.java
src/main/java/allclear/repository/subject/ClassInfoRepository.java
src/main/java/allclear/service/GradeService.java
src/main/java/allclear/service/MemberService.java
src/main/java/allclear/service/RequirementService.java
src/main/java/allclear/service/SubjectService.java

- 기존에 DB에 반영되지 않던 문제 해결
- 변경감지로 변경 및 ClassInfoRepository 생성 후 ClassInfo DB에서 삭제 후 다시 Set 해주는 방식으로 변경
- 잘못된 memberId가 입력으로 들어올 경우 예외 처리
- 크롤링 예외처리 추가, 크롤링과 파싱의 경우 분리

[Fix] 과목 업데이트 오류 수정 및 예외 처리

---

src/main/java/allclear/controller/SubjectController.java
src/main/java/allclear/dto/responseDto/subject/SubjectListResponseDto.java
src/main/java/allclear/repository/subject/SubjectRepository.java
src/main/java/allclear/service/SubjectService.java
src/test/java/allclear/SubjectServiceTest.java

#71 
- 과목 조회 페이징 기능 구현
- 과목 조회 post->get 으로 수정

[Feat] 과목 조회 페이징 기능 구현

---

src/main/java/allclear/controller/TimetableGeneratorController.java
src/main/java/allclear/global/response/ApiResponse.java

- TimetableGeneratorController data가 "" 부분 삭제
- ApiRespons data 없을 때 ""에서 null로 수정

[Refactor] ApiResponse 데이터 수정

---

src/main/java/allclear/crawl/CrawlMemberInfo.java
src/main/java/allclear/crawl/ParsingGrade.java
src/test/java/allclear/crawl/CrawalTest.java

- CrawlMemberInfo 내 함수 추가
- 과목 Id 리스트 저장
- CrawlMemberInfo 내 리스트로 저장
- 성적 항목 크롤링 오류 처리

[Feat]: 입학연도별 교과과정 크롤링 기능 추가

---

src/main/java/allclear/crawl/CrawlSubjectInfo.java
src/main/java/allclear/crawl/ParsingSubject.java
src/test/java/allclear/MemberServiceTest.java
src/test/java/allclear/crawl/CrawalTest.java
src/test/java/allclear/crawl/CrawlSubjectTest.java

[Fix:]과목 크롤링 에러 처리

---

src/main/java/allclear/service/MemberService.java

testUser 비밀번호 수정
시간표 생성기 member Set 추가

[Chore] testUser 비밀번호 수정

---

src/main/java/allclear/service/MemberService.java

시간표 생성기 member 연관관계 매핑 추가
memberUpdate에 시간표 생성기 업데이트 추가
코드 리펙터링
기능 테스트 완료한 주석 삭제

[Chore] memberService 수정

---

src/main/java/allclear/crawl/CrawlMemberInfo.java
src/test/java/allclear/crawl/CrawalTest.java

- 기존 id로 검색하던 방식에서 경로 검색 방식으로 변경

[Fix] 크롤링 에러 처리

---

src/main/java/allclear/controller/GradeController.java
src/main/java/allclear/controller/RequirementController.java
src/main/java/allclear/crawl/ParsingGrade.java
src/main/java/allclear/domain/grade/Grade.java
src/main/java/allclear/domain/grade/SemesterGrade.java
src/main/java/allclear/domain/grade/SemesterSubject.java
src/main/java/allclear/domain/requirement/Requirement.java
src/main/java/allclear/domain/requirement/RequirementComponent.java
src/main/java/allclear/dto/responseDto/grade/GradeResponseDto.java
src/main/java/allclear/dto/responseDto/grade/SemesterGradeResponseDto.java
src/main/java/allclear/dto/responseDto/grade/SemesterSubjectResponseDto.java
src/main/java/allclear/dto/responseDto/requirement/RequirementComponentResponseDto.java
src/main/java/allclear/dto/responseDto/requirement/RequirementResponseDto.java
src/main/java/allclear/service/GradeService.java
src/main/java/allclear/service/MemberService.java
src/main/java/allclear/service/RequirementService.java
src/test/java/allclear/crawl/RequirementTest.java

#80 
- Requirement , grade, subject 리팩토링
- setter 제거
- builder 패턴 적용

[Refactor] builder 패턴 적용

---

src/main/java/allclear/crawl/CrawlMemberInfo.java
src/main/java/allclear/crawl/ParsingGrade.java
src/main/java/allclear/crawl/ParsingRequirement.java
src/main/java/allclear/domain/grade/Grade.java
src/main/java/allclear/domain/grade/SemesterGrade.java
src/main/java/allclear/domain/requirement/Requirement.java
src/test/java/allclear/crawl/CrawalTest.java

[Fix] 크롤링 에러 수정

---

src/main/java/allclear/controller/TimetableGeneratorController.java
src/main/java/allclear/domain/timetableGenerator/TimetableGenerator.java
src/main/java/allclear/domain/timetableGenerator/TimetableGeneratorSubject.java
src/main/java/allclear/domain/timetableGenerator/TimetableGeneratorTimetable.java
src/main/java/allclear/domain/timetableGenerator/TimetableGeneratorTimetableSubject.java
src/main/java/allclear/dto/responseDto/timetable/TimetableResponseDto.java
src/main/java/allclear/dto/responseDto/timetableGenerator/Step3to6ResponseDto.java
src/main/java/allclear/repository/subject/SubjectSpecification.java
src/main/java/allclear/service/TimetableGeneratorManager.java

[Add] 과목 추천 메서드

---

src/main/java/allclear/service/TimetableGeneratorManager.java

chore:chor링chorcadcchsachccgidkㅇdㅇㅇcddb 삭제 반영

---

src/main/java/allclear/domain/timetableGenerator/TimetableGeneratorSubject.java
src/main/java/allclear/domain/timetableGenerator/TimetableGeneratorTimetable.java
src/main/java/allclear/service/TimetableGeneratorManager.java
src/test/java/allclear/TimetableGeneratorTest.java
src/test/resources/application.yml

[Add] 시간표 생성 함수

---

src/main/java/allclear/crawl/subject/CrawlSubjectInfo.java
src/main/java/allclear/crawl/subject/ParsingSubject.java

[Fix] 과목 크롤링 에러 처리

---

src/main/java/allclear/controller/TimetableGeneratorController.java
src/main/java/allclear/domain/timetableGenerator/TimetableGeneratorSubject.java
src/main/java/allclear/dto/requestDto/timetableGenerator/Step7RequestDto.java
src/main/java/allclear/dto/responseDto/timetableGenerator/Step8ResponseDto.java
src/main/java/allclear/global/exception/code/GlobalErrorCode.java
src/main/java/allclear/repository/timetableGenerator/TimetableGeneratorTimetableRepository.java
src/main/java/allclear/service/timetableGenerator/TimetableGeneratorManager.java
src/main/java/allclear/service/timetableGenerator/TimetableGeneratorService.java

- 학점 범위 선택 추가
- 전공 학점 범위 선택 추가
- 시간표 생성기 과목 필드에 전공 여부 추가
- 중복 시간표 제거

[Chore] 시간표 생성기 알고리즘 수정

---

src/main/java/allclear/crawl/subject/CrawlSubjectInfo.java
src/main/java/allclear/crawl/subject/ParsingSubject.java
src/main/java/allclear/domain/subject/Subject.java
src/main/java/allclear/service/SubjectService.java

- 교과영역 구분 크롤링 추가
- 기존 ClASS_INFO DB 저장 시 삭제 안되던 문제 처리

[Feat] 교과영역 구분 크롤링 추가 및 과목 업데이트 함수 오류 처리

---

src/main/java/allclear/crawl/subject/ChangeToUsaintSubjectName.java
src/main/java/allclear/crawl/subject/ParsingSubject.java

[Fix] 과목 파싱 오류 처리

---

src/main/java/allclear/repository/subject/SubjectRepositoryImpl.java

[Fix]: 과목 조회 함수 오류 수정

---

src/main/java/allclear/controller/TimetableController.java
src/main/java/allclear/domain/member/Member.java
src/main/java/allclear/dto/responseDto/MemberResponseDto.java
src/main/java/allclear/dto/responseDto/timetable/TimetableListResponseDto.java
src/main/java/allclear/service/MemberService.java
src/main/java/allclear/service/TimetableService.java

[Chore] 시간표 관련 API 수정

---

src/main/java/allclear/crawl/subject/ChangeToUsaintSubjectName.java
src/main/java/allclear/dto/requestDto/subject/SubjectSearchRequestDto.java
src/main/java/allclear/repository/subject/SubjectRepositoryImpl.java

- 과목 조건 검색 requestDto 변수명 변경
- 조건 검색 함수 UI에 맞게 예외 처리

[Chore] 과목 조건 requestDto 변수명 변경 및 조건 검색 함수 예외 처리
